import "./globals.css";

export const metadata = {
  title: "Building App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR">
      <body className={``}>{children}</body>
    </html>
  );
}
