export const fakeData = [
  {
    id: 1,
    name: "برج آسمان",
    location: "تهران",
    address: "سعادت‌آباد، خیابان سرو غربی، نبش خیابان آسمان",
    status: "در حال ساخت",
    startDate: "1402-03-15",
    endDate: "1404-08-20",
    engineer: "مهندس احمد رضایی",
    owner: "شرکت ساختمانی آسمان",
    units: 100,
    parkingSpaces: 150,
    area: 25000,
    description: "برج مسکونی 25 طبقه با امکانات مدرن شامل استخر و سالن ورزشی",
  },
  {
    id: 2,
    name: "مجتمع تجاری نور",
    location: "اصفهان",
    address: "چهارباغ بالا، خیابان شمس‌آبادی، پلاک 45",
    status: "تکمیل شده",
    startDate: "1400-01-10",
    endDate: "1402-12-25",
    engineer: "مهندس سارا حسینی",
    owner: "هلدینگ نور پارسی",
    units: 120,
    parkingSpaces: 200,
    area: 18000,
    description: "مرکز خرید با 120 واحد تجاری و پارکینگ طبقاتی",
  },
  {
    id: 3,
    name: "ویلا دریاکنار",
    location: "مازندران",
    address: "نوشهر، جاده دریاکنار، خیابان یاس، پلاک 12",
    status: "در حال طراحی",
    startDate: "1403-05-01",
    endDate: "1405-02-30",
    engineer: "مهندس محمد کاظمی",
    owner: "آقای رضا نعمتی",
    units: 1,
    parkingSpaces: 2,
    area: 300,
    description: "ویلا لوکس با منظره دریا و باغ اختصاصی",
  },
  {
    id: 4,
    name: "پل طبیعت جدید",
    location: "شیراز",
    address: "بلوار چمران، روبروی پارک ملت",
    status: "در حال ساخت",
    startDate: "1402-09-10",
    endDate: "1404-06-15",
    engineer: "مهندس لیلا محمدی",
    owner: "شهرداری شیراز",
    units: 0,
    parkingSpaces: 0,
    area: 500,
    description: "پل عابر پیاده با طراحی مدرن و نورپردازی ویژه",
  },
  {
    id: 5,
    name: "برج پارسیس",
    location: "تبریز",
    address: "ولیعصر، خیابان شهریار، پلاک 22",
    status: "در حال ساخت",
    startDate: "1402-07-01",
    endDate: "1404-10-30",
    engineer: "مهندس بهروز اکبری",
    owner: "شرکت پارسیس سازه",
    units: 80,
    parkingSpaces: 100,
    area: 20000,
    description: "برج مسکونی لوکس با 20 طبقه و سیستم هوشمند",
  },
  {
    id: 6,
    name: "مجتمع گلستان",
    location: "مشهد",
    address: "بلوار وکیل‌آباد، خیابان گلستان، پلاک 15",
    status: "تکمیل شده",
    startDate: "1399-04-20",
    endDate: "1401-11-10",
    engineer: "مهندس فاطمه رحیمی",
    owner: "تعاونی مسکن گلستان",
    units: 50,
    parkingSpaces: 60,
    area: 10000,
    description: "مجتمع مسکونی با واحدهای میان‌متراژ و فضای سبز",
  },
  {
    id: 7,
    name: "پارکینگ طبقاتی مرکزی",
    location: "کرج",
    address: "میدان توحید، خیابان شهید بهشتی",
    status: "در حال ساخت",
    startDate: "1402-02-05",
    endDate: "1403-12-15",
    engineer: "مهندس علی حسینی",
    owner: "شهرداری کرج",
    units: 0,
    parkingSpaces: 300,
    area: 8000,
    description: "پارکینگ طبقاتی برای کاهش ترافیک مرکز شهر",
  },
  {
    id: 8,
    name: "ویلا کوهستانی البرز",
    location: "البرز",
    address: "جاده چالوس، روستای وینه، پلاک 8",
    status: "تکمیل شده",
    startDate: "1401-06-15",
    endDate: "1402-09-20",
    engineer: "مهندس نگار صالحی",
    owner: "خانم سمیه احمدی",
    units: 1,
    parkingSpaces: 3,
    area: 250,
    description: "ویلا کوهستانی با معماری سنتی و مدرن",
  },
  {
    id: 9,
    name: "برج الماس",
    location: "اهواز",
    address: "کیانپارس، خیابان پهلوان شرقی، پلاک 30",
    status: "در حال طراحی",
    startDate: "1403-08-01",
    endDate: "1406-03-10",
    engineer: "مهندس رضا شریفی",
    owner: "شرکت الماس جنوب",
    units: 150,
    parkingSpaces: 200,
    area: 30000,
    description: "برج تجاری-مسکونی با 30 طبقه و امکانات رفاهی",
  },
  {
    id: 10,
    name: "مجتمع ساحلی کاسپین",
    location: "گیلان",
    address: "انزلی، خیابان ساحل قو، پلاک 50",
    status: "در حال ساخت",
    startDate: "1402-05-10",
    endDate: "1404-02-25",
    engineer: "مهندس مینا رضوی",
    owner: "شرکت کاسپین دریا",
    units: 40,
    parkingSpaces: 50,
    area: 12000,
    description: "مجتمع مسکونی ساحلی با دسترسی مستقیم به دریا",
  },
];
